from __future__ import annotations


def assess_model_uncertainty(distribution: list[dict]) -> dict:
    """Prototype ambiguity guardrail; not calibrated medical uncertainty."""
    if not distribution:
        return {
            "status": "uncertain",
            "reason": "No model distribution was available.",
        }

    scores = [float(item.get("score", 0.0)) for item in distribution]
    top1 = scores[0]
    top2 = scores[1] if len(scores) > 1 else 0.0
    margin = top1 - top2
    uncertain = top1 < 50.0 or margin < 10.0

    return {
        "status": "uncertain" if uncertain else "usable",
        "reason": (
            "The model output is relatively ambiguous. Use a clearer image "
            "and do not interpret the prediction as a diagnosis."
            if uncertain else
            "The classifier output is sufficiently concentrated for this prototype's contextual assessment flow."
        ),
        "top1_score": round(top1, 2),
        "top2_score": round(top2, 2),
        "margin": round(margin, 2),
    }


def determine_screening_priority(
    answers: list[dict],
    model_uncertainty: dict,
) -> str:
    """
    Deterministic prototype guardrail.

    Uses the structured question category generated by Gemini rather than
    arbitrary question IDs. This is NOT a clinical risk score.
    """
    if model_uncertainty.get("status") == "uncertain":
        return "Uncertain"

    concerning = 0

    for item in answers:
        category = str(item.get("category", "general")).lower()
        answer = str(item.get("answer", "")).lower()

        if category in {"change", "evolution", "growth"}:
            if "yes" in answer or "recent" in answer or "changed" in answer:
                concerning += 1

        elif category in {"bleeding", "crusting", "non_healing"}:
            if "yes" in answer or "bleed" in answer or "crust" in answer:
                concerning += 1

        elif category in {"symptoms", "pain", "itching"}:
            if "pain" in answer or "both" in answer or "severe" in answer:
                concerning += 1

    if concerning >= 2:
        return "Higher"
    if concerning >= 1:
        return "Moderate"
    return "Lower"
